export const contactsData = [
  {
    name: "Carlos Rodríguez",
    position: "Director General",
    email: "carlos.rodriguez@empet.cu",
    phone: "+53 7 555-1234",
    department: "Dirección General",
    linkedin: "https://linkedin.com/in/ejemplo",
  },
  {
    name: "María González",
    position: "Directora de Operaciones",
    email: "maria.gonzalez@empet.cu",
    phone: "+53 7 555-2345",
    department: "Operaciones",
    linkedin: "https://linkedin.com/in/ejemplo",
  },
  {
    name: "Javier Pérez",
    position: "Director Financiero",
    email: "javier.perez@empet.cu",
    phone: "+53 7 555-3456",
    department: "Finanzas",
    linkedin: "https://linkedin.com/in/ejemplo",
  },
  {
    name: "Laura Martínez",
    position: "Directora de Recursos Humanos",
    email: "laura.martinez@empet.cu",
    phone: "+53 7 555-4567",
    department: "Recursos Humanos",
    linkedin: null,
  },
  {
    name: "Roberto Fernández",
    position: "Director de Tecnología",
    email: "roberto.fernandez@empet.cu",
    phone: "+53 7 555-5678",
    department: "Tecnología e Innovación",
    linkedin: "https://linkedin.com/in/ejemplo",
  },
  {
    name: "Ana Sánchez",
    position: "Directora de Sostenibilidad",
    email: "ana.sanchez@empet.cu",
    phone: "+53 7 555-6789",
    department: "Sostenibilidad y Medio Ambiente",
    linkedin: "https://linkedin.com/in/ejemplo",
  },
]
